name: ci

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - run: dotnet restore DevellaSolution/DevellaSolution.sln
      - run: dotnet build DevellaSolution/DevellaSolution.sln -c Release --no-restore
      - run: dotnet test DevellaSolution/DevellaSolution.sln -c Release --no-build
